/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.1.12.v201907221221.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/

#ifndef V1_PROJ_DCLUSTER_MCUMANAGER_MCU_MANAGER_TYPES_DBUS_DEPLOYMENT_HPP_
#define V1_PROJ_DCLUSTER_MCUMANAGER_MCU_MANAGER_TYPES_DBUS_DEPLOYMENT_HPP_

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif
#include <CommonAPI/DBus/DBusDeployment.hpp>
#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace proj {
namespace dcluster {
namespace McuManager {
namespace McuManagerTypes_ {

// typecollection-specific deployment types
typedef CommonAPI::EmptyDeployment EnumValueDisplayTypeDeployment_t;

typedef CommonAPI::EmptyDeployment EnumDrivingStateDeployment_t;

typedef CommonAPI::EmptyDeployment EnumLanguageTypeDeployment_t;

typedef CommonAPI::EmptyDeployment EnumAreaTypeDeployment_t;

typedef CommonAPI::EmptyDeployment EnumEngineTypeDeployment_t;

typedef CommonAPI::EmptyDeployment EnumSpeedoTypeDeployment_t;

typedef CommonAPI::EmptyDeployment EnumMissionTypeDeployment_t;

typedef CommonAPI::EmptyDeployment EnumBodyTypeDeployment_t;

typedef CommonAPI::EmptyDeployment EnumPlatformTypeDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StVariantInfoDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StEOLInfoDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StSWVariantInfoDeployment_t;

typedef CommonAPI::EmptyDeployment EnumStreerWheelKeyDeployment_t;

typedef CommonAPI::EmptyDeployment EnumIGNStateDeployment_t;

typedef CommonAPI::EmptyDeployment EnumSpeedoUnitDeployment_t;

typedef CommonAPI::EmptyDeployment EnumTemperatureUnitDeployment_t;

typedef CommonAPI::EmptyDeployment EnumFuelUnitDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StTripValue8Deployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StTripValue16Deployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::IntegerDeployment
> StTripValue32Deployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::EmptyDeployment
> StTripDTEInfoDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StTripFuelEconomyInfoDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::DBus::IntegerDeployment
    >,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StTripAccumulatedInfoDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::DBus::IntegerDeployment
    >,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StTripDriveInfoDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::EmptyDeployment
> StTripSpeedMeterDeployment_t;

typedef CommonAPI::EmptyDeployment EnumDriveModeDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StDriveModeInfoDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StDriveModeBarDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >
> StTripDriveModeInfoDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StEngineCoolantTempDeployment_t;

typedef CommonAPI::EmptyDeployment EnumPowerFlowDeployment_t;

typedef CommonAPI::EmptyDeployment EnumTransmissionTempLevelDeployment_t;

typedef CommonAPI::EmptyDeployment EnumTBTDisplayTypeDeployment_t;

typedef CommonAPI::EmptyDeployment EnumTBTPageStateDeployment_t;

typedef CommonAPI::EmptyDeployment EnumTBTPointTypeDeployment_t;

typedef CommonAPI::EmptyDeployment EnumTBTDistanceUnitDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StTBTDistanceDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >
> StTBTDistDestInfoDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::EmptyDeployment
> StTBTTurnInfoDeployment_t;

typedef CommonAPI::EmptyDeployment EnumTBTTimeFormatDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StTBTDestinationTimeDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StTBTRemainTimeDeployment_t;

typedef CommonAPI::EmptyDeployment TPDataDeployment_t;

typedef CommonAPI::EmptyDeployment EnumCruiseCtrlDisplayTypeDeployment_t;

typedef CommonAPI::EmptyDeployment EnumCruiseCtrlDisplayType2Deployment_t;

typedef CommonAPI::EmptyDeployment EnumCruiseCtrlSymbolTypeDeployment_t;

typedef CommonAPI::EmptyDeployment EnumCruiseCtrlSymbolStatusDeployment_t;

typedef CommonAPI::EmptyDeployment EnumCruiseCtrlDispColorDeployment_t;

typedef CommonAPI::EmptyDeployment EnumCruiseCtrlObjGapLevelDeployment_t;

typedef CommonAPI::EmptyDeployment EnumCruiseCtrlTauGapLevelDeployment_t;

typedef CommonAPI::EmptyDeployment EnumCruiseCtrlAutoDispTypeDeployment_t;

typedef CommonAPI::EmptyDeployment EnumSCCTargetDispTypeDeployment_t;

typedef CommonAPI::EmptyDeployment EnumADASDispTypeDeployment_t;

typedef CommonAPI::EmptyDeployment EnumADASVehicleIdDeployment_t;

typedef CommonAPI::EmptyDeployment EnumADASVehicleStatusDeployment_t;

typedef CommonAPI::EmptyDeployment EnumADASLaneTypeDeployment_t;

typedef CommonAPI::EmptyDeployment EnumADASLCAvailStatusDeployment_t;

typedef CommonAPI::EmptyDeployment EnumADASLaneActiveDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StSccSetSpeedDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StSCCSymbolDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StDriveAssistCCInfoTTCDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StCCObjectDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >
> StSCCVehicleInfoDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >
> StSCCTargetDistInfoDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::DBus::StructDeployment<
            CommonAPI::EmptyDeployment,
            CommonAPI::EmptyDeployment,
            CommonAPI::EmptyDeployment
        >
    >,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::DBus::StructDeployment<
            CommonAPI::EmptyDeployment,
            CommonAPI::EmptyDeployment,
            CommonAPI::EmptyDeployment
        >
    >,
    CommonAPI::EmptyDeployment
> StDriveAssistCCInfoRealDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::EmptyDeployment
> StADASVehicleInfoDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StADASLaneInfoDeployment_t;

typedef CommonAPI::DBus::ArrayDeployment<
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::DBus::StructDeployment<
            CommonAPI::EmptyDeployment,
            CommonAPI::EmptyDeployment,
            CommonAPI::EmptyDeployment
        >,
        CommonAPI::EmptyDeployment
    >
> VehicleInfoListDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::ArrayDeployment<
        CommonAPI::DBus::StructDeployment<
            CommonAPI::EmptyDeployment,
            CommonAPI::EmptyDeployment,
            CommonAPI::DBus::StructDeployment<
                CommonAPI::EmptyDeployment,
                CommonAPI::EmptyDeployment,
                CommonAPI::EmptyDeployment
            >,
            CommonAPI::EmptyDeployment
        >
    >,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >
> StAdasInfoDeployment_t;

typedef CommonAPI::EmptyDeployment EnumLaneContentsTypeDeployment_t;

typedef CommonAPI::EmptyDeployment EnumLaneDisplayTypeDeployment_t;

typedef CommonAPI::EmptyDeployment EnumLaneStateDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StDriveAssistLaneInfoDeployment_t;

typedef CommonAPI::EmptyDeployment EnumDAWDisplayTypeDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StDAWTimeValueDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >
> StDriveAssistDAWInfoDeployment_t;

typedef CommonAPI::EmptyDeployment EnumISLWDisplayTypeDeployment_t;

typedef CommonAPI::EmptyDeployment EnumISLWProhibitionTypeDeployment_t;

typedef CommonAPI::EmptyDeployment EnumISLWCondSignOptionTypeDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StISLWCondSignInfoDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >
> StDriveAssistISLWInfoDeployment_t;

typedef CommonAPI::EmptyDeployment EnumTPMSDisplayTypeDeployment_t;

typedef CommonAPI::EmptyDeployment EnumTPMSPressureUnitDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StTPMSTireInfoDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >
> StDriveAssistTPMSInfoDeployment_t;

typedef CommonAPI::EmptyDeployment EnumAWDAngleDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StDriveAssistAWDInfoDeployment_t;

typedef CommonAPI::EmptyDeployment EnumEnergyFlowDisplayTypeDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StEnergyFlowInfoDeployment_t;

typedef CommonAPI::EmptyDeployment EnumMyDrvModeDispTypeDeployment_t;

typedef CommonAPI::EmptyDeployment EnumMyDrvModeFocusDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StFuelEffValueDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >
> StMyDrvModeInfoDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::EmptyDeployment
> StContentsDTEDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StContentsOATDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::DBus::IntegerDeployment
    >,
    CommonAPI::EmptyDeployment
> StContentsODODeployment_t;

typedef CommonAPI::EmptyDeployment EnumGearStateDeployment_t;

typedef CommonAPI::EmptyDeployment EnumGearTargetDeployment_t;

typedef CommonAPI::EmptyDeployment EnumGearArrowDeployment_t;

typedef CommonAPI::EmptyDeployment EnumGearBlinkStateDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StContentsGearInfoDeployment_t;

typedef CommonAPI::EmptyDeployment EnumContentsCCDispTypeDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StContentsCCValueDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >
> StContentsCCInfoDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StContentsObjectInfoDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StContentsSCCDistanceDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >
> StContentsSCCInfoDeployment_t;

typedef CommonAPI::EmptyDeployment EnumContentsCoastingDispTypeDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StContentsCoastingDeployment_t;

typedef CommonAPI::EmptyDeployment EnumDISDispTypeDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StDISSpdValueDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StDISItemDeployment_t;

typedef CommonAPI::DBus::ArrayDeployment<
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >
> DISListDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::DBus::ArrayDeployment<
        CommonAPI::DBus::StructDeployment<
            CommonAPI::EmptyDeployment,
            CommonAPI::EmptyDeployment
        >
    >,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >
> StContentsDISInfoDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StContentsISLWInfoDeployment_t;

typedef CommonAPI::EmptyDeployment EnumEcoPwrDispStateDeployment_t;

typedef CommonAPI::EmptyDeployment EnumContentsRSBRStateDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StContentsRSBRInfoDeployment_t;

typedef CommonAPI::EmptyDeployment EnumContentsSpdLimitDispTypeDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StMSLAValueDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >
> StContentsSpdLimitInfoDeployment_t;

typedef CommonAPI::EmptyDeployment EnumEventDisplayTypeDeployment_t;

typedef CommonAPI::EmptyDeployment EnumFactoryScreenTypeDeployment_t;

typedef CommonAPI::EmptyDeployment EnumEventIDDeployment_t;

typedef CommonAPI::EmptyDeployment EventDataDeployment_t;

typedef CommonAPI::DBus::ArrayDeployment<
    CommonAPI::EmptyDeployment
> MasterWarnTableDeployment_t;

typedef CommonAPI::EmptyDeployment EnumMasterWarnCmdDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StEventContentsInfoDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> StSoundInfoDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DRIVER_ASSIST_SCC_REACTION_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DRIVER_ASSIST_DRIVING_ASSIST_LEADING_DEPARTURE_ALERT_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DRIVER_ASSIST_DRIVING_ASSIST_LANE_FOLLOWING_ASSIST_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DRIVER_ASSIST_DRIVING_ASSIST_HIGHWAY_DRIVING_ASSIST_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DRIVER_ASSIST_DRIVING_ASSIST_HIGHWAY_AUTO_SPEED_ZONE_SLOWDOWN_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DRIVER_ASSIST_DRIVING_ASSIST_HIGHWAY_AUTO_CURVE_SLOWDOWN_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DRIVER_ASSIST_DRIVING_ASSIST_SPEED_LIMIT_WARNING_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DRIVER_ASSIST_DRIVER_ATTENTION_WARNING_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DRIVER_ASSIST_WARNING_TIMING_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DRIVER_ASSIST_WARNING_VOLUME_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DRIVER_ASSIST_LANE_SAFETY_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DRIVER_ASSIST_LANE_SAFETY_MODE_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DRIVER_ASSIST_FORWARD_SAFETY_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DRIVER_ASSIST_BLIND_SPOT_SAFETY_SPOT_VIEW_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DRIVER_ASSIST_BLIND_SPOT_SAFETY_SAFETY_EXIT_ASSIST_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DRIVER_ASSIST_BLIND_SPOT_SAFETY_WARNING_ONLY_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DRIVER_ASSIST_BLIND_SPOT_SAFETY_REAR_CROSS_TRAFFIC_SAFETY_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DOOR_AUTO_LOCK_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DOOR_AUTO_UNLOCK_KEY_OR_POWER_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DOOR_AUTO_UNLOCK_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DOOR_HORN_FEEDBACK_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DOOR_POWER_TAILGATE_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DOOR_POWER_TAILGATE_SPEED_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_DOOR_SMART_TAILGATE_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_LIGHTS_ONE_TOUCH_TURN_SIGNAL_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_LIGHTS_AMBIENT_LIGHT_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_LIGHTS_HEADLIGHT_DELAY_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_LIGHTS_HIGH_BEAM_ASSIST_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_SOUND_CLUSTER_VOICE_GUIDANCE_VOLUME_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_SOUND_PARK_ASSIST_VOLUME_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_SOUND_WELCOME_SOUND_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_CONVENIENCE_SEAT_EASY_ACCESS_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_CONVENIENCE_WELCOME_MIRROR_LIGHT_TITLE_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_CONVENIENCE_WELCOME_MIRROR_LIGHT_ON_DOOR_UNLOCK_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_CONVENIENCE_WELCOME_MIRROR_LIGHT_ON_DRIVER_APPROACH_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_CONVENIENCE_MIRROR_AUTO_FOLDING_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_CONVENIENCE_WIRELESS_CHARGING_SYSTEM_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_CONVENIENCE_TRAFFIC_INFORMATION_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_CONVENIENCE_WIPER_LIGHTS_DISPLAY_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_CONVENIENCE_AUTO_REAR_WIPER_IN_R_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_CONVENIENCE_GEAR_POSITION_POPUP_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_CONVENIENCE_ICY_ROAD_WARNING_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_SERVICE_INTERVAL_MODE_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_SERVICE_INTERVAL_ENABLE_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_OTHER_FUEL_ECONOMY_RESET_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_OTHER_FUEL_ECONOMY_UNIT_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_OTHER_TEMPERATURE_UNIT_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_OTHER_TIRE_PRESSURE_UNIT_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_OTHER_SPEED_UNIT_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_OTHER_TORQUE_UNIT_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_OTHER_TURBO_BOOST_PRESSURE_UNIT_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_ECO_VEHICLE_GREEN_ZONE_EV_DRIVE_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_ECO_VEHICLE_COASTING_GUIDE_ENABLE_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_ECO_VEHICLE_COASTING_GUIDE_SOUND_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_ECO_VEHICLE_START_COASTING_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_ECO_VEHICLE_CHARGING_CONNECTOR_LOCKING_MODE_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_ECO_VEHICLE_CHARGING_CONNECTOR_CONDITIONDeployment_t;

typedef CommonAPI::EmptyDeployment USM_ECO_VEHICLE_AUXILIARY_BATTERY_SAVER_PLUS_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_ECO_VEHICLE_VOLUME_CONTROL_FUNCTION_FOR_VESS_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USM_LANGUAGE_VALUEDeployment_t;

typedef CommonAPI::EmptyDeployment USMItemIndexDeployment_t;

typedef CommonAPI::EmptyDeployment SetUSMResultDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::IntegerDeployment
> USMItem32Deployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::DBus::IntegerDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::IntegerDeployment,
    CommonAPI::DBus::IntegerDeployment
> USMServiceReminderDeployment_t;

typedef CommonAPI::EmptyDeployment CmdDataDeployment_t;

typedef CommonAPI::EmptyDeployment TabIndexDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> GroupTabInfoDeployment_t;


// typecollection-specific deployments

} // namespace McuManagerTypes_
} // namespace McuManager
} // namespace dcluster
} // namespace proj
} // namespace v1

#endif // V1_PROJ_DCLUSTER_MCUMANAGER_MCU_MANAGER_TYPES_DBUS_DEPLOYMENT_HPP_
