/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.1.12.v201907221221.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1/proj/dcluster/McuManager/McuManagerDBusProxy.hpp>

namespace v1 {
namespace proj {
namespace dcluster {
namespace McuManager {

std::shared_ptr<CommonAPI::DBus::DBusProxy> createMcuManagerDBusProxy(
    const CommonAPI::DBus::DBusAddress &_address,
    const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection) {
    return std::make_shared< McuManagerDBusProxy>(_address, _connection);
}

void initializeMcuManagerDBusProxy() {
     CommonAPI::DBus::Factory::get()->registerProxyCreateMethod(
        McuManager::getInterface(),
        &createMcuManagerDBusProxy);
}

INITIALIZER(registerMcuManagerDBusProxy) {
    CommonAPI::DBus::Factory::get()->registerInterface(initializeMcuManagerDBusProxy);
}

McuManagerDBusProxy::McuManagerDBusProxy(
    const CommonAPI::DBus::DBusAddress &_address,
    const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection)
    :   CommonAPI::DBus::DBusProxy(_address, _connection)
,        mainContentsDisplayControl_(*this, "onMainContentsDisplayControlAttributeChanged", "setMainContentsDisplayControlAttribute", "b", "getMainContentsDisplayControlAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        drivingState_(*this, "onDrivingStateAttributeChanged", "setDrivingStateAttribute", "i", "getDrivingStateAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        driveMode_(*this, "onDriveModeAttributeChanged", "setDriveModeAttribute", "(ii)", "getDriveModeAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StDriveModeInfoDeployment_t* >(nullptr)),
        variant_(*this, "onVariantAttributeChanged", "setVariantAttribute", "(iiiiii)", "getVariantAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StVariantInfoDeployment_t* >(nullptr)),
        eOL_(*this, "onEOLAttributeChanged", "setEOLAttribute", "(yyyyyyyyyyyyyyi)", "getEOLAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StEOLInfoDeployment_t* >(nullptr)),
        sWVariant_(*this, "onSWVariantAttributeChanged", "setSWVariantAttribute", "(yyyyyyyyyyyyyyyyyyyyyyyyyyy)", "getSWVariantAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StSWVariantInfoDeployment_t* >(nullptr)),
        iGN1State_(*this, "onIGN1StateAttributeChanged", "setIGN1StateAttribute", "i", "getIGN1StateAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        iGN3State_(*this, "onIGN3StateAttributeChanged", "setIGN3StateAttribute", "i", "getIGN3StateAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        speedoUnit_(*this, "onSpeedoUnitAttributeChanged", "setSpeedoUnitAttribute", "i", "getSpeedoUnitAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        tripDriveMode_(*this, "onTripDriveModeAttributeChanged", "setTripDriveModeAttribute", "(i(iy))", "getTripDriveModeAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StTripDriveModeInfoDeployment_t* >(nullptr)),
        tripDTE_(*this, "onTripDTEAttributeChanged", "setTripDTEAttribute", "((iq)(iq)i)", "getTripDTEAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StTripDTEInfoDeployment_t* >(nullptr)),
        tripFuelEconomy_(*this, "onTripFuelEconomyAttributeChanged", "setTripFuelEconomyAttribute", "((iq)(iq)ib)", "getTripFuelEconomyAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StTripFuelEconomyInfoDeployment_t* >(nullptr)),
        tripAccumulated_(*this, "onTripAccumulatedAttributeChanged", "setTripAccumulatedAttribute", "((iu)(iq)(iq)(iq)ii)", "getTripAccumulatedAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StTripAccumulatedInfoDeployment_t* >(nullptr)),
        tripDriveInfo_(*this, "onTripDriveInfoAttributeChanged", "setTripDriveInfoAttribute", "((iu)(iq)(iq)(iq)ii)", "getTripDriveInfoAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StTripDriveInfoDeployment_t* >(nullptr)),
        tripDigitalSpeedMeter_(*this, "onTripDigitalSpeedMeterAttributeChanged", "setTripDigitalSpeedMeterAttribute", "((iq)i)", "getTripDigitalSpeedMeterAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StTripSpeedMeterDeployment_t* >(nullptr)),
        tripPowerFlowDiagram_(*this, "onTripPowerFlowDiagramAttributeChanged", "setTripPowerFlowDiagramAttribute", "i", "getTripPowerFlowDiagramAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        tripUREALevel_(*this, "onTripUREALevelAttributeChanged", "setTripUREALevelAttribute", "y", "getTripUREALevelAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        tripTransmissionTemp_(*this, "onTripTransmissionTempAttributeChanged", "setTripTransmissionTempAttribute", "i", "getTripTransmissionTempAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        tripEngineCoolantTemp_(*this, "onTripEngineCoolantTempAttributeChanged", "setTripEngineCoolantTempAttribute", "(iiy)", "getTripEngineCoolantTempAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StEngineCoolantTempDeployment_t* >(nullptr)),
        energyFlow_(*this, "onEnergyFlowAttributeChanged", "setEnergyFlowAttribute", "(iy)", "getEnergyFlowAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StEnergyFlowInfoDeployment_t* >(nullptr)),
        myDrivingMode_(*this, "onMyDrivingModeAttributeChanged", "setMyDrivingModeAttribute", "(ii(iy)(iy)(iy))", "getMyDrivingModeAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StMyDrvModeInfoDeployment_t* >(nullptr)),
        tBTDisplayType_(*this, "onTBTDisplayTypeAttributeChanged", "setTBTDisplayTypeAttribute", "i", "getTBTDisplayTypeAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        tBTDisplayTollgate_(*this, "onTBTDisplayTollgateAttributeChanged", "setTBTDisplayTollgateAttribute", "b", "getTBTDisplayTollgateAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        tBTPreliminaryInfo_(*this, "onTBTPreliminaryInfoAttributeChanged", "setTBTPreliminaryInfoAttribute", "y", "getTBTPreliminaryInfoAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        tBTDestInfoPageState_(*this, "onTBTDestInfoPageStateAttributeChanged", "setTBTDestInfoPageStateAttribute", "i", "getTBTDestInfoPageStateAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        tBTPointType_(*this, "onTBTPointTypeAttributeChanged", "setTBTPointTypeAttribute", "i", "getTBTPointTypeAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        tBTDirection_(*this, "onTBTDirectionAttributeChanged", "setTBTDirectionAttribute", "y", "getTBTDirectionAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        tBTRoadDisplay_(*this, "onTBTRoadDisplayAttributeChanged", "setTBTRoadDisplayAttribute", "q", "getTBTRoadDisplayAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        tBTSideRoadDisplay_(*this, "onTBTSideRoadDisplayAttributeChanged", "setTBTSideRoadDisplayAttribute", "y", "getTBTSideRoadDisplayAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        tBTDistanceToDestination_(*this, "onTBTDistanceToDestinationAttributeChanged", "setTBTDistanceToDestinationAttribute", "(i(qyi))", "getTBTDistanceToDestinationAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StTBTDistDestInfoDeployment_t* >(nullptr)),
        tBTDistanceUntilTurn_(*this, "onTBTDistanceUntilTurnAttributeChanged", "setTBTDistanceUntilTurnAttribute", "(i(qyi)y)", "getTBTDistanceUntilTurnAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StTBTTurnInfoDeployment_t* >(nullptr)),
        tBTExpectedDestTime_(*this, "onTBTExpectedDestTimeAttributeChanged", "setTBTExpectedDestTimeAttribute", "(iiyy)", "getTBTExpectedDestTimeAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StTBTDestinationTimeDeployment_t* >(nullptr)),
        tBTExpectedRemainTime_(*this, "onTBTExpectedRemainTimeAttributeChanged", "setTBTExpectedRemainTimeAttribute", "(iyy)", "getTBTExpectedRemainTimeAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StTBTRemainTimeDeployment_t* >(nullptr)),
        tBTGuideTPInfo_(*this, "onTBTGuideTPInfoAttributeChanged", "setTBTGuideTPInfoAttribute", "ay", "getTBTGuideTPInfoAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        tBTDestTPInfo_(*this, "onTBTDestTPInfoAttributeChanged", "setTBTDestTPInfoAttribute", "ay", "getTBTDestTPInfoAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        tBTViaPoint1TPInfo_(*this, "onTBTViaPoint1TPInfoAttributeChanged", "setTBTViaPoint1TPInfoAttribute", "ay", "getTBTViaPoint1TPInfoAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        tBTViaPoint2TPInfo_(*this, "onTBTViaPoint2TPInfoAttributeChanged", "setTBTViaPoint2TPInfoAttribute", "ay", "getTBTViaPoint2TPInfoAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        tBTViaPoint3TPInfo_(*this, "onTBTViaPoint3TPInfoAttributeChanged", "setTBTViaPoint3TPInfoAttribute", "ay", "getTBTViaPoint3TPInfoAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        tBTViaPoint4TPInfo_(*this, "onTBTViaPoint4TPInfoAttributeChanged", "setTBTViaPoint4TPInfoAttribute", "ay", "getTBTViaPoint4TPInfoAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        driveAssistCruiseControlTTC_(*this, "onDriveAssistCruiseControlTTCAttributeChanged", "setDriveAssistCruiseControlTTCAttribute", "(ii(ii)(iiby)bii)", "getDriveAssistCruiseControlTTCAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StDriveAssistCCInfoTTCDeployment_t* >(nullptr)),
        driveAssistCruiseControlReal_(*this, "onDriveAssistCruiseControlRealAttributeChanged", "setDriveAssistCruiseControlRealAttribute", "(i(i(qqd))(ib(qqd))b)", "getDriveAssistCruiseControlRealAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StDriveAssistCCInfoRealDeployment_t* >(nullptr)),
        driveAssistLane_(*this, "onDriveAssistLaneAttributeChanged", "setDriveAssistLaneAttribute", "(iiiib)", "getDriveAssistLaneAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StDriveAssistLaneInfoDeployment_t* >(nullptr)),
        driveAssistDAW_(*this, "onDriveAssistDAWAttributeChanged", "setDriveAssistDAWAttribute", "(i(iq))", "getDriveAssistDAWAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StDriveAssistDAWInfoDeployment_t* >(nullptr)),
        driveAssistISLW_(*this, "onDriveAssistISLWAttributeChanged", "setDriveAssistISLWAttribute", "(iyi(iyi)(iyi))", "getDriveAssistISLWAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StDriveAssistISLWInfoDeployment_t* >(nullptr)),
        driveAssistAWD_(*this, "onDriveAssistAWDAttributeChanged", "setDriveAssistAWDAttribute", "(iyy)", "getDriveAssistAWDAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StDriveAssistAWDInfoDeployment_t* >(nullptr)),
        driveAssistTPMS_(*this, "onDriveAssistTPMSAttributeChanged", "setDriveAssistTPMSAttribute", "(ii(ibqqd)(ibqqd)(ibqqd)(ibqqd))", "getDriveAssistTPMSAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StDriveAssistTPMSInfoDeployment_t* >(nullptr)),
        adasInfo_(*this, "onAdasInfoAttributeChanged", "setAdasInfoAttribute", "(ia(ii(qqd)i)(iiiiyqq))", "getAdasInfoAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StAdasInfoDeployment_t* >(nullptr)),
        contentsGear_(*this, "onContentsGearAttributeChanged", "setContentsGearAttribute", "(iiii)", "getContentsGearAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StContentsGearInfoDeployment_t* >(nullptr)),
        contentsCC_(*this, "onContentsCCAttributeChanged", "setContentsCCAttribute", "(i(iy))", "getContentsCCAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StContentsCCInfoDeployment_t* >(nullptr)),
        contentsSCC_(*this, "onContentsSCCAttributeChanged", "setContentsSCCAttribute", "(ii(ii)(iiby)(bbi)(ii))", "getContentsSCCAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StContentsSCCInfoDeployment_t* >(nullptr)),
        contentsCoasting_(*this, "onContentsCoastingAttributeChanged", "setContentsCoastingAttribute", "(ib)", "getContentsCoastingAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StContentsCoastingDeployment_t* >(nullptr)),
        contentsDIS_(*this, "onContentsDISAttributeChanged", "setContentsDISAttribute", "(a(iy)(iy))", "getContentsDISAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StContentsDISInfoDeployment_t* >(nullptr)),
        contentsDTEInfo_(*this, "onContentsDTEInfoAttributeChanged", "setContentsDTEInfoAttribute", "(i(iq)i)", "getContentsDTEInfoAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StContentsDTEDeployment_t* >(nullptr)),
        contentsISLW_(*this, "onContentsISLWAttributeChanged", "setContentsISLWAttribute", "(iyib)", "getContentsISLWAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StContentsISLWInfoDeployment_t* >(nullptr)),
        contentsOAT_(*this, "onContentsOATAttributeChanged", "setContentsOATAttribute", "(i(iy)ii)", "getContentsOATAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StContentsOATDeployment_t* >(nullptr)),
        contentsODOMeter_(*this, "onContentsODOMeterAttributeChanged", "setContentsODOMeterAttribute", "((iu)i)", "getContentsODOMeterAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StContentsODODeployment_t* >(nullptr)),
        ecoPowerDisplayInfo_(*this, "onEcoPowerDisplayInfoAttributeChanged", "setEcoPowerDisplayInfoAttribute", "i", "getEcoPowerDisplayInfoAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        contentsRSBR_(*this, "onContentsRSBRAttributeChanged", "setContentsRSBRAttribute", "(iiii)", "getContentsRSBRAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StContentsRSBRInfoDeployment_t* >(nullptr)),
        contentsSpeedLimit_(*this, "onContentsSpeedLimitAttributeChanged", "setContentsSpeedLimitAttribute", "(i(iy))", "getContentsSpeedLimitAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StContentsSpdLimitInfoDeployment_t* >(nullptr)),
        masterWarnCmd_(*this, "onMasterWarnCmdAttributeChanged", "setMasterWarnCmdAttribute", "i", "getMasterWarnCmdAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        avTpAMFMInfo_(*this, "onAvTpAMFMInfoAttributeChanged", "setAvTpAMFMInfoAttribute", "ay", "getAvTpAMFMInfoAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        avTpXMInfo_(*this, "onAvTpXMInfoAttributeChanged", "setAvTpXMInfoAttribute", "ay", "getAvTpXMInfoAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        avTpDABInfo_(*this, "onAvTpDABInfoAttributeChanged", "setAvTpDABInfoAttribute", "ay", "getAvTpDABInfoAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        avTpDMBInfo_(*this, "onAvTpDMBInfoAttributeChanged", "setAvTpDMBInfoAttribute", "ay", "getAvTpDMBInfoAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        avTpJukeBoxInfo_(*this, "onAvTpJukeBoxInfoAttributeChanged", "setAvTpJukeBoxInfoAttribute", "ay", "getAvTpJukeBoxInfoAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        avTpIpodInfo_(*this, "onAvTpIpodInfoAttributeChanged", "setAvTpIpodInfoAttribute", "ay", "getAvTpIpodInfoAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        avTpUSBInfo_(*this, "onAvTpUSBInfoAttributeChanged", "setAvTpUSBInfoAttribute", "ay", "getAvTpUSBInfoAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        avTpBlueToothInfo_(*this, "onAvTpBlueToothInfoAttributeChanged", "setAvTpBlueToothInfoAttribute", "ay", "getAvTpBlueToothInfoAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        avTpAppleCarPlayInfo_(*this, "onAvTpAppleCarPlayInfoAttributeChanged", "setAvTpAppleCarPlayInfoAttribute", "ay", "getAvTpAppleCarPlayInfoAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        avTpAndroidAutoInfo_(*this, "onAvTpAndroidAutoInfoAttributeChanged", "setAvTpAndroidAutoInfoAttribute", "ay", "getAvTpAndroidAutoInfoAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        avTpIboxInfo_(*this, "onAvTpIboxInfoAttributeChanged", "setAvTpIboxInfoAttribute", "ay", "getAvTpIboxInfoAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        avTpCDInfo_(*this, "onAvTpCDInfoAttributeChanged", "setAvTpCDInfoAttribute", "ay", "getAvTpCDInfoAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        avTpBaiduMInfo_(*this, "onAvTpBaiduMInfoAttributeChanged", "setAvTpBaiduMInfoAttribute", "ay", "getAvTpBaiduMInfoAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        eventContentsFull_(*this, "onEventContentsFullAttributeChanged", "setEventContentsFullAttribute", "(iibay)", "getEventContentsFullAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StEventContentsInfoDeployment_t* >(nullptr)),
        eventContentsMini_(*this, "onEventContentsMiniAttributeChanged", "setEventContentsMiniAttribute", "(iibay)", "getEventContentsMiniAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StEventContentsInfoDeployment_t* >(nullptr)),
        eventAccessory_(*this, "onEventAccessoryAttributeChanged", "setEventAccessoryAttribute", "b", "getEventAccessoryAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        powerTailGateWarnState_(*this, "onPowerTailGateWarnStateAttributeChanged", "setPowerTailGateWarnStateAttribute", "b", "getPowerTailGateWarnStateAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        displayLanguage_(*this, "onDisplayLanguageAttributeChanged", "setDisplayLanguageAttribute", "i", "getDisplayLanguageAttribute", static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
        usmDriverAssist_SccReaction_(*this, "onUsmDriverAssist_SccReactionAttributeChanged", "(ii)", "getUsmDriverAssist_SccReactionAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmDriverAssist_DrivingAssist_LeadingVehicleDepartureAlert_(*this, "onUsmDriverAssist_DrivingAssist_LeadingVehicleDepartureAlertAttributeChanged", "(ii)", "getUsmDriverAssist_DrivingAssist_LeadingVehicleDepartureAlertAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmDriverAssist_DrivingAssist_LaneFollowingAssist_(*this, "onUsmDriverAssist_DrivingAssist_LaneFollowingAssistAttributeChanged", "(ii)", "getUsmDriverAssist_DrivingAssist_LaneFollowingAssistAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmDriverAssist_DrivingAssist_HighwayDrivingAssist_(*this, "onUsmDriverAssist_DrivingAssist_HighwayDrivingAssistAttributeChanged", "(ii)", "getUsmDriverAssist_DrivingAssist_HighwayDrivingAssistAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmDriverAssist_DrivingAssist_HighwayAutoSpeedZoneSlowDown_(*this, "onUsmDriverAssist_DrivingAssist_HighwayAutoSpeedZoneSlowDownAttributeChanged", "(ii)", "getUsmDriverAssist_DrivingAssist_HighwayAutoSpeedZoneSlowDownAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmDriverAssist_DrivingAssist_HighwayAutoCurveSlowDown_(*this, "onUsmDriverAssist_DrivingAssist_HighwayAutoCurveSlowDownAttributeChanged", "(ii)", "getUsmDriverAssist_DrivingAssist_HighwayAutoCurveSlowDownAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmDriverAssist_DrivingAssist_SpeedLimitWarning_(*this, "onUsmDriverAssist_DrivingAssist_SpeedLimitWarningAttributeChanged", "(ii)", "getUsmDriverAssist_DrivingAssist_SpeedLimitWarningAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmDriverAssist_DriverAttentionWarning_(*this, "onUsmDriverAssist_DriverAttentionWarningAttributeChanged", "(ii)", "getUsmDriverAssist_DriverAttentionWarningAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmDriverAssist_WarningTiming_(*this, "onUsmDriverAssist_WarningTimingAttributeChanged", "(ii)", "getUsmDriverAssist_WarningTimingAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmDriverAssist_WarningVolume_(*this, "onUsmDriverAssist_WarningVolumeAttributeChanged", "(ii)", "getUsmDriverAssist_WarningVolumeAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmDriverAssist_LaneSafety_(*this, "onUsmDriverAssist_LaneSafetyAttributeChanged", "(ii)", "getUsmDriverAssist_LaneSafetyAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmDriverAssist_LaneSafety_Mode_(*this, "onUsmDriverAssist_LaneSafety_ModeAttributeChanged", "(ii)", "getUsmDriverAssist_LaneSafety_ModeAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmDriverAssist_ForwardSafety_(*this, "onUsmDriverAssist_ForwardSafetyAttributeChanged", "(ii)", "getUsmDriverAssist_ForwardSafetyAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmDriverAssist_BlindSpotSafety_SpotView_(*this, "onUsmDriverAssist_BlindSpotSafety_SpotViewAttributeChanged", "(ii)", "getUsmDriverAssist_BlindSpotSafety_SpotViewAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmDriverAssist_BlindSpotSafety_SafetyExitAssist_(*this, "onUsmDriverAssist_BlindSpotSafety_SafetyExitAssistAttributeChanged", "(ii)", "getUsmDriverAssist_BlindSpotSafety_SafetyExitAssistAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmDriverAssist_BlindSpotSafety_WarningOnly_(*this, "onUsmDriverAssist_BlindSpotSafety_WarningOnlyAttributeChanged", "(ii)", "getUsmDriverAssist_BlindSpotSafety_WarningOnlyAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmDriverAssist_BlindSpotSafety_RearCrossTrafficSafety_(*this, "onUsmDriverAssist_BlindSpotSafety_RearCrossTrafficSafetyAttributeChanged", "(ii)", "getUsmDriverAssist_BlindSpotSafety_RearCrossTrafficSafetyAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmDoor_AutoLock_(*this, "onUsmDoor_AutoLockAttributeChanged", "(ii)", "getUsmDoor_AutoLockAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmDoor_AutoUnlock_KeyOrPower_(*this, "onUsmDoor_AutoUnlock_KeyOrPowerAttributeChanged", "(ii)", "getUsmDoor_AutoUnlock_KeyOrPowerAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmDoor_AutoUnlock_(*this, "onUsmDoor_AutoUnlockAttributeChanged", "(ii)", "getUsmDoor_AutoUnlockAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmDoor_HornFeedback_(*this, "onUsmDoor_HornFeedbackAttributeChanged", "(ii)", "getUsmDoor_HornFeedbackAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmDoor_PowerTailgate_(*this, "onUsmDoor_PowerTailgateAttributeChanged", "(ii)", "getUsmDoor_PowerTailgateAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmDoor_PowerTailgateSpeed_(*this, "onUsmDoor_PowerTailgateSpeedAttributeChanged", "(ii)", "getUsmDoor_PowerTailgateSpeedAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmDoor_SmartTailgate_(*this, "onUsmDoor_SmartTailgateAttributeChanged", "(ii)", "getUsmDoor_SmartTailgateAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmLights_OneTouchTurnSignal_(*this, "onUsmLights_OneTouchTurnSignalAttributeChanged", "(ii)", "getUsmLights_OneTouchTurnSignalAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmLights_AmbientLight_(*this, "onUsmLights_AmbientLightAttributeChanged", "(ii)", "getUsmLights_AmbientLightAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmLights_HeadlightDelay_(*this, "onUsmLights_HeadlightDelayAttributeChanged", "(ii)", "getUsmLights_HeadlightDelayAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmLights_HighBeamAssist_(*this, "onUsmLights_HighBeamAssistAttributeChanged", "(ii)", "getUsmLights_HighBeamAssistAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmSound_ClusterVoiceGuidanceVolume_(*this, "onUsmSound_ClusterVoiceGuidanceVolumeAttributeChanged", "(ii)", "getUsmSound_ClusterVoiceGuidanceVolumeAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmSound_ParkAssistVolume_(*this, "onUsmSound_ParkAssistVolumeAttributeChanged", "(ii)", "getUsmSound_ParkAssistVolumeAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmSound_WelcomeSound_(*this, "onUsmSound_WelcomeSoundAttributeChanged", "(ii)", "getUsmSound_WelcomeSoundAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmConvenience_SeatEasyAccess_(*this, "onUsmConvenience_SeatEasyAccessAttributeChanged", "(ii)", "getUsmConvenience_SeatEasyAccessAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmConvenience_WelcomeMirrorLight_Title_(*this, "onUsmConvenience_WelcomeMirrorLight_TitleAttributeChanged", "(ii)", "getUsmConvenience_WelcomeMirrorLight_TitleAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmConvenience_WelcomeMirrorLight_OnDoorUnlock_(*this, "onUsmConvenience_WelcomeMirrorLight_OnDoorUnlockAttributeChanged", "(ii)", "getUsmConvenience_WelcomeMirrorLight_OnDoorUnlockAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmConvenience_WelcomeMirrorLight_OnDriverApproach_(*this, "onUsmConvenience_WelcomeMirrorLight_OnDriverApproachAttributeChanged", "(ii)", "getUsmConvenience_WelcomeMirrorLight_OnDriverApproachAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmConvenience_MirrorAutoFolding_(*this, "onUsmConvenience_MirrorAutoFoldingAttributeChanged", "(ii)", "getUsmConvenience_MirrorAutoFoldingAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmConvenience_WirelessChargingSystem_(*this, "onUsmConvenience_WirelessChargingSystemAttributeChanged", "(ii)", "getUsmConvenience_WirelessChargingSystemAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmConvenience_TrafficInformation_(*this, "onUsmConvenience_TrafficInformationAttributeChanged", "(ii)", "getUsmConvenience_TrafficInformationAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmConvenience_WipreLightsDisplay_(*this, "onUsmConvenience_WipreLightsDisplayAttributeChanged", "(ii)", "getUsmConvenience_WipreLightsDisplayAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmConvenience_AutoRearWiperInR_(*this, "onUsmConvenience_AutoRearWiperInRAttributeChanged", "(ii)", "getUsmConvenience_AutoRearWiperInRAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmConvenience_GearPositionPopup_(*this, "onUsmConvenience_GearPositionPopupAttributeChanged", "(ii)", "getUsmConvenience_GearPositionPopupAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmConvenience_IcyRoadWarning_(*this, "onUsmConvenience_IcyRoadWarningAttributeChanged", "(ii)", "getUsmConvenience_IcyRoadWarningAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmServiceInterval_Mode_(*this, "onUsmServiceInterval_ModeAttributeChanged", "(ii)", "getUsmServiceInterval_ModeAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmServiceInterval_EnableServiceInterval_(*this, "onUsmServiceInterval_EnableServiceIntervalAttributeChanged", "(ii)", "getUsmServiceInterval_EnableServiceIntervalAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmServiceInterval_Reset_(*this, "onUsmServiceInterval_ResetAttributeChanged", "(ii)", "getUsmServiceInterval_ResetAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmOther_FuelEconomyReset_(*this, "onUsmOther_FuelEconomyResetAttributeChanged", "(ii)", "getUsmOther_FuelEconomyResetAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmOther_FuelEconomyUnit_(*this, "onUsmOther_FuelEconomyUnitAttributeChanged", "(ii)", "getUsmOther_FuelEconomyUnitAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmOther_TemperatureUnit_(*this, "onUsmOther_TemperatureUnitAttributeChanged", "(ii)", "getUsmOther_TemperatureUnitAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmOther_TirePressureUnit_(*this, "onUsmOther_TirePressureUnitAttributeChanged", "(ii)", "getUsmOther_TirePressureUnitAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmOther_SpeedUnit_(*this, "onUsmOther_SpeedUnitAttributeChanged", "(ii)", "getUsmOther_SpeedUnitAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmOther_TorqueUnit_(*this, "onUsmOther_TorqueUnitAttributeChanged", "(ii)", "getUsmOther_TorqueUnitAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmOther_TurboBoostPressureUnit_(*this, "onUsmOther_TurboBoostPressureUnitAttributeChanged", "(ii)", "getUsmOther_TurboBoostPressureUnitAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmEcoVehicle_GreenZoneEVDrive_(*this, "onUsmEcoVehicle_GreenZoneEVDriveAttributeChanged", "(ii)", "getUsmEcoVehicle_GreenZoneEVDriveAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmEcoVehicle_CoastingGuideEnable_(*this, "onUsmEcoVehicle_CoastingGuideEnableAttributeChanged", "(ii)", "getUsmEcoVehicle_CoastingGuideEnableAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmEcoVehicle_CoastingGuideSound_(*this, "onUsmEcoVehicle_CoastingGuideSoundAttributeChanged", "(ii)", "getUsmEcoVehicle_CoastingGuideSoundAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmEcoVehicle_StartCoasting_(*this, "onUsmEcoVehicle_StartCoastingAttributeChanged", "(ii)", "getUsmEcoVehicle_StartCoastingAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmEcoVehicle_ChargingConnectorLockingMode_(*this, "onUsmEcoVehicle_ChargingConnectorLockingModeAttributeChanged", "(ii)", "getUsmEcoVehicle_ChargingConnectorLockingModeAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmEcoVehicle_ChargingConnectorCondition_(*this, "onUsmEcoVehicle_ChargingConnectorConditionAttributeChanged", "(ii)", "getUsmEcoVehicle_ChargingConnectorConditionAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmEcoVehicle_AuxiliaryBatterySaverPlus_(*this, "onUsmEcoVehicle_AuxiliaryBatterySaverPlusAttributeChanged", "(ii)", "getUsmEcoVehicle_AuxiliaryBatterySaverPlusAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmLanguage_(*this, "onUsmLanguageAttributeChanged", "(ii)", "getUsmLanguageAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        usmService_Reminder_(*this, "onUsmService_ReminderAttributeChanged", "(uqii)", "getUsmService_ReminderAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMServiceReminderDeployment_t* >(nullptr)),
        usmEcoVehicle_VolumeControlFunctionForVESS_(*this, "onUsmEcoVehicle_VolumeControlFunctionForVESSAttributeChanged", "(ii)", "getUsmEcoVehicle_VolumeControlFunctionForVESSAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::USMItem32Deployment_t* >(nullptr)),
        lastTabInfo_(*this, "onLastTabInfoAttributeChanged", "(iyyy)", "getLastTabInfoAttribute", static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::GroupTabInfoDeployment_t* >(nullptr))
,        notifySteerWheelKey_(*this, "NotifySteerWheelKey", "i", std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr))),
        notifyIGNState_(*this, "NotifyIGNState", "i", std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr))),
        notifyContentsGearState_(*this, "NotifyContentsGearState", "(iiii)", std::make_tuple(static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StContentsGearInfoDeployment_t* >(nullptr))),
        notifyEventContents_(*this, "NotifyEventContents", "(iibay)", std::make_tuple(static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StEventContentsInfoDeployment_t* >(nullptr))),
        notifyMasterWarnInfo_(*this, "NotifyMasterWarnInfo", "", std::make_tuple()),
        notifyMasterWarnCmd_(*this, "NotifyMasterWarnCmd", "i", std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr))),
        notifySound_(*this, "NotifySound", "(yyy)(yyy)(yyy)(yyy)", std::make_tuple(static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StSoundInfoDeployment_t* >(nullptr), static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StSoundInfoDeployment_t* >(nullptr), static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StSoundInfoDeployment_t* >(nullptr), static_cast< ::v1::proj::dcluster::McuManager::McuManagerTypes_::StSoundInfoDeployment_t* >(nullptr)))
{
}

      McuManagerDBusProxy::MainContentsDisplayControlAttribute& McuManagerDBusProxy::getMainContentsDisplayControlAttribute() {
          return mainContentsDisplayControl_;
      }
      McuManagerDBusProxy::DrivingStateAttribute& McuManagerDBusProxy::getDrivingStateAttribute() {
          return drivingState_;
      }
      McuManagerDBusProxy::DriveModeAttribute& McuManagerDBusProxy::getDriveModeAttribute() {
          return driveMode_;
      }
      McuManagerDBusProxy::VariantAttribute& McuManagerDBusProxy::getVariantAttribute() {
          return variant_;
      }
      McuManagerDBusProxy::EOLAttribute& McuManagerDBusProxy::getEOLAttribute() {
          return eOL_;
      }
      McuManagerDBusProxy::SWVariantAttribute& McuManagerDBusProxy::getSWVariantAttribute() {
          return sWVariant_;
      }
      McuManagerDBusProxy::IGN1StateAttribute& McuManagerDBusProxy::getIGN1StateAttribute() {
          return iGN1State_;
      }
      McuManagerDBusProxy::IGN3StateAttribute& McuManagerDBusProxy::getIGN3StateAttribute() {
          return iGN3State_;
      }
      McuManagerDBusProxy::SpeedoUnitAttribute& McuManagerDBusProxy::getSpeedoUnitAttribute() {
          return speedoUnit_;
      }
      McuManagerDBusProxy::TripDriveModeAttribute& McuManagerDBusProxy::getTripDriveModeAttribute() {
          return tripDriveMode_;
      }
      McuManagerDBusProxy::TripDTEAttribute& McuManagerDBusProxy::getTripDTEAttribute() {
          return tripDTE_;
      }
      McuManagerDBusProxy::TripFuelEconomyAttribute& McuManagerDBusProxy::getTripFuelEconomyAttribute() {
          return tripFuelEconomy_;
      }
      McuManagerDBusProxy::TripAccumulatedAttribute& McuManagerDBusProxy::getTripAccumulatedAttribute() {
          return tripAccumulated_;
      }
      McuManagerDBusProxy::TripDriveInfoAttribute& McuManagerDBusProxy::getTripDriveInfoAttribute() {
          return tripDriveInfo_;
      }
      McuManagerDBusProxy::TripDigitalSpeedMeterAttribute& McuManagerDBusProxy::getTripDigitalSpeedMeterAttribute() {
          return tripDigitalSpeedMeter_;
      }
      McuManagerDBusProxy::TripPowerFlowDiagramAttribute& McuManagerDBusProxy::getTripPowerFlowDiagramAttribute() {
          return tripPowerFlowDiagram_;
      }
      McuManagerDBusProxy::TripUREALevelAttribute& McuManagerDBusProxy::getTripUREALevelAttribute() {
          return tripUREALevel_;
      }
      McuManagerDBusProxy::TripTransmissionTempAttribute& McuManagerDBusProxy::getTripTransmissionTempAttribute() {
          return tripTransmissionTemp_;
      }
      McuManagerDBusProxy::TripEngineCoolantTempAttribute& McuManagerDBusProxy::getTripEngineCoolantTempAttribute() {
          return tripEngineCoolantTemp_;
      }
      McuManagerDBusProxy::EnergyFlowAttribute& McuManagerDBusProxy::getEnergyFlowAttribute() {
          return energyFlow_;
      }
      McuManagerDBusProxy::MyDrivingModeAttribute& McuManagerDBusProxy::getMyDrivingModeAttribute() {
          return myDrivingMode_;
      }
      McuManagerDBusProxy::TBTDisplayTypeAttribute& McuManagerDBusProxy::getTBTDisplayTypeAttribute() {
          return tBTDisplayType_;
      }
      McuManagerDBusProxy::TBTDisplayTollgateAttribute& McuManagerDBusProxy::getTBTDisplayTollgateAttribute() {
          return tBTDisplayTollgate_;
      }
      McuManagerDBusProxy::TBTPreliminaryInfoAttribute& McuManagerDBusProxy::getTBTPreliminaryInfoAttribute() {
          return tBTPreliminaryInfo_;
      }
      McuManagerDBusProxy::TBTDestInfoPageStateAttribute& McuManagerDBusProxy::getTBTDestInfoPageStateAttribute() {
          return tBTDestInfoPageState_;
      }
      McuManagerDBusProxy::TBTPointTypeAttribute& McuManagerDBusProxy::getTBTPointTypeAttribute() {
          return tBTPointType_;
      }
      McuManagerDBusProxy::TBTDirectionAttribute& McuManagerDBusProxy::getTBTDirectionAttribute() {
          return tBTDirection_;
      }
      McuManagerDBusProxy::TBTRoadDisplayAttribute& McuManagerDBusProxy::getTBTRoadDisplayAttribute() {
          return tBTRoadDisplay_;
      }
      McuManagerDBusProxy::TBTSideRoadDisplayAttribute& McuManagerDBusProxy::getTBTSideRoadDisplayAttribute() {
          return tBTSideRoadDisplay_;
      }
      McuManagerDBusProxy::TBTDistanceToDestinationAttribute& McuManagerDBusProxy::getTBTDistanceToDestinationAttribute() {
          return tBTDistanceToDestination_;
      }
      McuManagerDBusProxy::TBTDistanceUntilTurnAttribute& McuManagerDBusProxy::getTBTDistanceUntilTurnAttribute() {
          return tBTDistanceUntilTurn_;
      }
      McuManagerDBusProxy::TBTExpectedDestTimeAttribute& McuManagerDBusProxy::getTBTExpectedDestTimeAttribute() {
          return tBTExpectedDestTime_;
      }
      McuManagerDBusProxy::TBTExpectedRemainTimeAttribute& McuManagerDBusProxy::getTBTExpectedRemainTimeAttribute() {
          return tBTExpectedRemainTime_;
      }
      McuManagerDBusProxy::TBTGuideTPInfoAttribute& McuManagerDBusProxy::getTBTGuideTPInfoAttribute() {
          return tBTGuideTPInfo_;
      }
      McuManagerDBusProxy::TBTDestTPInfoAttribute& McuManagerDBusProxy::getTBTDestTPInfoAttribute() {
          return tBTDestTPInfo_;
      }
      McuManagerDBusProxy::TBTViaPoint1TPInfoAttribute& McuManagerDBusProxy::getTBTViaPoint1TPInfoAttribute() {
          return tBTViaPoint1TPInfo_;
      }
      McuManagerDBusProxy::TBTViaPoint2TPInfoAttribute& McuManagerDBusProxy::getTBTViaPoint2TPInfoAttribute() {
          return tBTViaPoint2TPInfo_;
      }
      McuManagerDBusProxy::TBTViaPoint3TPInfoAttribute& McuManagerDBusProxy::getTBTViaPoint3TPInfoAttribute() {
          return tBTViaPoint3TPInfo_;
      }
      McuManagerDBusProxy::TBTViaPoint4TPInfoAttribute& McuManagerDBusProxy::getTBTViaPoint4TPInfoAttribute() {
          return tBTViaPoint4TPInfo_;
      }
      McuManagerDBusProxy::DriveAssistCruiseControlTTCAttribute& McuManagerDBusProxy::getDriveAssistCruiseControlTTCAttribute() {
          return driveAssistCruiseControlTTC_;
      }
      McuManagerDBusProxy::DriveAssistCruiseControlRealAttribute& McuManagerDBusProxy::getDriveAssistCruiseControlRealAttribute() {
          return driveAssistCruiseControlReal_;
      }
      McuManagerDBusProxy::DriveAssistLaneAttribute& McuManagerDBusProxy::getDriveAssistLaneAttribute() {
          return driveAssistLane_;
      }
      McuManagerDBusProxy::DriveAssistDAWAttribute& McuManagerDBusProxy::getDriveAssistDAWAttribute() {
          return driveAssistDAW_;
      }
      McuManagerDBusProxy::DriveAssistISLWAttribute& McuManagerDBusProxy::getDriveAssistISLWAttribute() {
          return driveAssistISLW_;
      }
      McuManagerDBusProxy::DriveAssistAWDAttribute& McuManagerDBusProxy::getDriveAssistAWDAttribute() {
          return driveAssistAWD_;
      }
      McuManagerDBusProxy::DriveAssistTPMSAttribute& McuManagerDBusProxy::getDriveAssistTPMSAttribute() {
          return driveAssistTPMS_;
      }
      McuManagerDBusProxy::AdasInfoAttribute& McuManagerDBusProxy::getAdasInfoAttribute() {
          return adasInfo_;
      }
      McuManagerDBusProxy::ContentsGearAttribute& McuManagerDBusProxy::getContentsGearAttribute() {
          return contentsGear_;
      }
      McuManagerDBusProxy::ContentsCCAttribute& McuManagerDBusProxy::getContentsCCAttribute() {
          return contentsCC_;
      }
      McuManagerDBusProxy::ContentsSCCAttribute& McuManagerDBusProxy::getContentsSCCAttribute() {
          return contentsSCC_;
      }
      McuManagerDBusProxy::ContentsCoastingAttribute& McuManagerDBusProxy::getContentsCoastingAttribute() {
          return contentsCoasting_;
      }
      McuManagerDBusProxy::ContentsDISAttribute& McuManagerDBusProxy::getContentsDISAttribute() {
          return contentsDIS_;
      }
      McuManagerDBusProxy::ContentsDTEInfoAttribute& McuManagerDBusProxy::getContentsDTEInfoAttribute() {
          return contentsDTEInfo_;
      }
      McuManagerDBusProxy::ContentsISLWAttribute& McuManagerDBusProxy::getContentsISLWAttribute() {
          return contentsISLW_;
      }
      McuManagerDBusProxy::ContentsOATAttribute& McuManagerDBusProxy::getContentsOATAttribute() {
          return contentsOAT_;
      }
      McuManagerDBusProxy::ContentsODOMeterAttribute& McuManagerDBusProxy::getContentsODOMeterAttribute() {
          return contentsODOMeter_;
      }
      McuManagerDBusProxy::EcoPowerDisplayInfoAttribute& McuManagerDBusProxy::getEcoPowerDisplayInfoAttribute() {
          return ecoPowerDisplayInfo_;
      }
      McuManagerDBusProxy::ContentsRSBRAttribute& McuManagerDBusProxy::getContentsRSBRAttribute() {
          return contentsRSBR_;
      }
      McuManagerDBusProxy::ContentsSpeedLimitAttribute& McuManagerDBusProxy::getContentsSpeedLimitAttribute() {
          return contentsSpeedLimit_;
      }
      McuManagerDBusProxy::MasterWarnCmdAttribute& McuManagerDBusProxy::getMasterWarnCmdAttribute() {
          return masterWarnCmd_;
      }
      McuManagerDBusProxy::AvTpAMFMInfoAttribute& McuManagerDBusProxy::getAvTpAMFMInfoAttribute() {
          return avTpAMFMInfo_;
      }
      McuManagerDBusProxy::AvTpXMInfoAttribute& McuManagerDBusProxy::getAvTpXMInfoAttribute() {
          return avTpXMInfo_;
      }
      McuManagerDBusProxy::AvTpDABInfoAttribute& McuManagerDBusProxy::getAvTpDABInfoAttribute() {
          return avTpDABInfo_;
      }
      McuManagerDBusProxy::AvTpDMBInfoAttribute& McuManagerDBusProxy::getAvTpDMBInfoAttribute() {
          return avTpDMBInfo_;
      }
      McuManagerDBusProxy::AvTpJukeBoxInfoAttribute& McuManagerDBusProxy::getAvTpJukeBoxInfoAttribute() {
          return avTpJukeBoxInfo_;
      }
      McuManagerDBusProxy::AvTpIpodInfoAttribute& McuManagerDBusProxy::getAvTpIpodInfoAttribute() {
          return avTpIpodInfo_;
      }
      McuManagerDBusProxy::AvTpUSBInfoAttribute& McuManagerDBusProxy::getAvTpUSBInfoAttribute() {
          return avTpUSBInfo_;
      }
      McuManagerDBusProxy::AvTpBlueToothInfoAttribute& McuManagerDBusProxy::getAvTpBlueToothInfoAttribute() {
          return avTpBlueToothInfo_;
      }
      McuManagerDBusProxy::AvTpAppleCarPlayInfoAttribute& McuManagerDBusProxy::getAvTpAppleCarPlayInfoAttribute() {
          return avTpAppleCarPlayInfo_;
      }
      McuManagerDBusProxy::AvTpAndroidAutoInfoAttribute& McuManagerDBusProxy::getAvTpAndroidAutoInfoAttribute() {
          return avTpAndroidAutoInfo_;
      }
      McuManagerDBusProxy::AvTpIboxInfoAttribute& McuManagerDBusProxy::getAvTpIboxInfoAttribute() {
          return avTpIboxInfo_;
      }
      McuManagerDBusProxy::AvTpCDInfoAttribute& McuManagerDBusProxy::getAvTpCDInfoAttribute() {
          return avTpCDInfo_;
      }
      McuManagerDBusProxy::AvTpBaiduMInfoAttribute& McuManagerDBusProxy::getAvTpBaiduMInfoAttribute() {
          return avTpBaiduMInfo_;
      }
      McuManagerDBusProxy::EventContentsFullAttribute& McuManagerDBusProxy::getEventContentsFullAttribute() {
          return eventContentsFull_;
      }
      McuManagerDBusProxy::EventContentsMiniAttribute& McuManagerDBusProxy::getEventContentsMiniAttribute() {
          return eventContentsMini_;
      }
      McuManagerDBusProxy::EventAccessoryAttribute& McuManagerDBusProxy::getEventAccessoryAttribute() {
          return eventAccessory_;
      }
      McuManagerDBusProxy::PowerTailGateWarnStateAttribute& McuManagerDBusProxy::getPowerTailGateWarnStateAttribute() {
          return powerTailGateWarnState_;
      }
      McuManagerDBusProxy::DisplayLanguageAttribute& McuManagerDBusProxy::getDisplayLanguageAttribute() {
          return displayLanguage_;
      }
      McuManagerDBusProxy::UsmDriverAssist_SccReactionAttribute& McuManagerDBusProxy::getUsmDriverAssist_SccReactionAttribute() {
          return usmDriverAssist_SccReaction_;
      }
      McuManagerDBusProxy::UsmDriverAssist_DrivingAssist_LeadingVehicleDepartureAlertAttribute& McuManagerDBusProxy::getUsmDriverAssist_DrivingAssist_LeadingVehicleDepartureAlertAttribute() {
          return usmDriverAssist_DrivingAssist_LeadingVehicleDepartureAlert_;
      }
      McuManagerDBusProxy::UsmDriverAssist_DrivingAssist_LaneFollowingAssistAttribute& McuManagerDBusProxy::getUsmDriverAssist_DrivingAssist_LaneFollowingAssistAttribute() {
          return usmDriverAssist_DrivingAssist_LaneFollowingAssist_;
      }
      McuManagerDBusProxy::UsmDriverAssist_DrivingAssist_HighwayDrivingAssistAttribute& McuManagerDBusProxy::getUsmDriverAssist_DrivingAssist_HighwayDrivingAssistAttribute() {
          return usmDriverAssist_DrivingAssist_HighwayDrivingAssist_;
      }
      McuManagerDBusProxy::UsmDriverAssist_DrivingAssist_HighwayAutoSpeedZoneSlowDownAttribute& McuManagerDBusProxy::getUsmDriverAssist_DrivingAssist_HighwayAutoSpeedZoneSlowDownAttribute() {
          return usmDriverAssist_DrivingAssist_HighwayAutoSpeedZoneSlowDown_;
      }
      McuManagerDBusProxy::UsmDriverAssist_DrivingAssist_HighwayAutoCurveSlowDownAttribute& McuManagerDBusProxy::getUsmDriverAssist_DrivingAssist_HighwayAutoCurveSlowDownAttribute() {
          return usmDriverAssist_DrivingAssist_HighwayAutoCurveSlowDown_;
      }
      McuManagerDBusProxy::UsmDriverAssist_DrivingAssist_SpeedLimitWarningAttribute& McuManagerDBusProxy::getUsmDriverAssist_DrivingAssist_SpeedLimitWarningAttribute() {
          return usmDriverAssist_DrivingAssist_SpeedLimitWarning_;
      }
      McuManagerDBusProxy::UsmDriverAssist_DriverAttentionWarningAttribute& McuManagerDBusProxy::getUsmDriverAssist_DriverAttentionWarningAttribute() {
          return usmDriverAssist_DriverAttentionWarning_;
      }
      McuManagerDBusProxy::UsmDriverAssist_WarningTimingAttribute& McuManagerDBusProxy::getUsmDriverAssist_WarningTimingAttribute() {
          return usmDriverAssist_WarningTiming_;
      }
      McuManagerDBusProxy::UsmDriverAssist_WarningVolumeAttribute& McuManagerDBusProxy::getUsmDriverAssist_WarningVolumeAttribute() {
          return usmDriverAssist_WarningVolume_;
      }
      McuManagerDBusProxy::UsmDriverAssist_LaneSafetyAttribute& McuManagerDBusProxy::getUsmDriverAssist_LaneSafetyAttribute() {
          return usmDriverAssist_LaneSafety_;
      }
      McuManagerDBusProxy::UsmDriverAssist_LaneSafety_ModeAttribute& McuManagerDBusProxy::getUsmDriverAssist_LaneSafety_ModeAttribute() {
          return usmDriverAssist_LaneSafety_Mode_;
      }
      McuManagerDBusProxy::UsmDriverAssist_ForwardSafetyAttribute& McuManagerDBusProxy::getUsmDriverAssist_ForwardSafetyAttribute() {
          return usmDriverAssist_ForwardSafety_;
      }
      McuManagerDBusProxy::UsmDriverAssist_BlindSpotSafety_SpotViewAttribute& McuManagerDBusProxy::getUsmDriverAssist_BlindSpotSafety_SpotViewAttribute() {
          return usmDriverAssist_BlindSpotSafety_SpotView_;
      }
      McuManagerDBusProxy::UsmDriverAssist_BlindSpotSafety_SafetyExitAssistAttribute& McuManagerDBusProxy::getUsmDriverAssist_BlindSpotSafety_SafetyExitAssistAttribute() {
          return usmDriverAssist_BlindSpotSafety_SafetyExitAssist_;
      }
      McuManagerDBusProxy::UsmDriverAssist_BlindSpotSafety_WarningOnlyAttribute& McuManagerDBusProxy::getUsmDriverAssist_BlindSpotSafety_WarningOnlyAttribute() {
          return usmDriverAssist_BlindSpotSafety_WarningOnly_;
      }
      McuManagerDBusProxy::UsmDriverAssist_BlindSpotSafety_RearCrossTrafficSafetyAttribute& McuManagerDBusProxy::getUsmDriverAssist_BlindSpotSafety_RearCrossTrafficSafetyAttribute() {
          return usmDriverAssist_BlindSpotSafety_RearCrossTrafficSafety_;
      }
      McuManagerDBusProxy::UsmDoor_AutoLockAttribute& McuManagerDBusProxy::getUsmDoor_AutoLockAttribute() {
          return usmDoor_AutoLock_;
      }
      McuManagerDBusProxy::UsmDoor_AutoUnlock_KeyOrPowerAttribute& McuManagerDBusProxy::getUsmDoor_AutoUnlock_KeyOrPowerAttribute() {
          return usmDoor_AutoUnlock_KeyOrPower_;
      }
      McuManagerDBusProxy::UsmDoor_AutoUnlockAttribute& McuManagerDBusProxy::getUsmDoor_AutoUnlockAttribute() {
          return usmDoor_AutoUnlock_;
      }
      McuManagerDBusProxy::UsmDoor_HornFeedbackAttribute& McuManagerDBusProxy::getUsmDoor_HornFeedbackAttribute() {
          return usmDoor_HornFeedback_;
      }
      McuManagerDBusProxy::UsmDoor_PowerTailgateAttribute& McuManagerDBusProxy::getUsmDoor_PowerTailgateAttribute() {
          return usmDoor_PowerTailgate_;
      }
      McuManagerDBusProxy::UsmDoor_PowerTailgateSpeedAttribute& McuManagerDBusProxy::getUsmDoor_PowerTailgateSpeedAttribute() {
          return usmDoor_PowerTailgateSpeed_;
      }
      McuManagerDBusProxy::UsmDoor_SmartTailgateAttribute& McuManagerDBusProxy::getUsmDoor_SmartTailgateAttribute() {
          return usmDoor_SmartTailgate_;
      }
      McuManagerDBusProxy::UsmLights_OneTouchTurnSignalAttribute& McuManagerDBusProxy::getUsmLights_OneTouchTurnSignalAttribute() {
          return usmLights_OneTouchTurnSignal_;
      }
      McuManagerDBusProxy::UsmLights_AmbientLightAttribute& McuManagerDBusProxy::getUsmLights_AmbientLightAttribute() {
          return usmLights_AmbientLight_;
      }
      McuManagerDBusProxy::UsmLights_HeadlightDelayAttribute& McuManagerDBusProxy::getUsmLights_HeadlightDelayAttribute() {
          return usmLights_HeadlightDelay_;
      }
      McuManagerDBusProxy::UsmLights_HighBeamAssistAttribute& McuManagerDBusProxy::getUsmLights_HighBeamAssistAttribute() {
          return usmLights_HighBeamAssist_;
      }
      McuManagerDBusProxy::UsmSound_ClusterVoiceGuidanceVolumeAttribute& McuManagerDBusProxy::getUsmSound_ClusterVoiceGuidanceVolumeAttribute() {
          return usmSound_ClusterVoiceGuidanceVolume_;
      }
      McuManagerDBusProxy::UsmSound_ParkAssistVolumeAttribute& McuManagerDBusProxy::getUsmSound_ParkAssistVolumeAttribute() {
          return usmSound_ParkAssistVolume_;
      }
      McuManagerDBusProxy::UsmSound_WelcomeSoundAttribute& McuManagerDBusProxy::getUsmSound_WelcomeSoundAttribute() {
          return usmSound_WelcomeSound_;
      }
      McuManagerDBusProxy::UsmConvenience_SeatEasyAccessAttribute& McuManagerDBusProxy::getUsmConvenience_SeatEasyAccessAttribute() {
          return usmConvenience_SeatEasyAccess_;
      }
      McuManagerDBusProxy::UsmConvenience_WelcomeMirrorLight_TitleAttribute& McuManagerDBusProxy::getUsmConvenience_WelcomeMirrorLight_TitleAttribute() {
          return usmConvenience_WelcomeMirrorLight_Title_;
      }
      McuManagerDBusProxy::UsmConvenience_WelcomeMirrorLight_OnDoorUnlockAttribute& McuManagerDBusProxy::getUsmConvenience_WelcomeMirrorLight_OnDoorUnlockAttribute() {
          return usmConvenience_WelcomeMirrorLight_OnDoorUnlock_;
      }
      McuManagerDBusProxy::UsmConvenience_WelcomeMirrorLight_OnDriverApproachAttribute& McuManagerDBusProxy::getUsmConvenience_WelcomeMirrorLight_OnDriverApproachAttribute() {
          return usmConvenience_WelcomeMirrorLight_OnDriverApproach_;
      }
      McuManagerDBusProxy::UsmConvenience_MirrorAutoFoldingAttribute& McuManagerDBusProxy::getUsmConvenience_MirrorAutoFoldingAttribute() {
          return usmConvenience_MirrorAutoFolding_;
      }
      McuManagerDBusProxy::UsmConvenience_WirelessChargingSystemAttribute& McuManagerDBusProxy::getUsmConvenience_WirelessChargingSystemAttribute() {
          return usmConvenience_WirelessChargingSystem_;
      }
      McuManagerDBusProxy::UsmConvenience_TrafficInformationAttribute& McuManagerDBusProxy::getUsmConvenience_TrafficInformationAttribute() {
          return usmConvenience_TrafficInformation_;
      }
      McuManagerDBusProxy::UsmConvenience_WipreLightsDisplayAttribute& McuManagerDBusProxy::getUsmConvenience_WipreLightsDisplayAttribute() {
          return usmConvenience_WipreLightsDisplay_;
      }
      McuManagerDBusProxy::UsmConvenience_AutoRearWiperInRAttribute& McuManagerDBusProxy::getUsmConvenience_AutoRearWiperInRAttribute() {
          return usmConvenience_AutoRearWiperInR_;
      }
      McuManagerDBusProxy::UsmConvenience_GearPositionPopupAttribute& McuManagerDBusProxy::getUsmConvenience_GearPositionPopupAttribute() {
          return usmConvenience_GearPositionPopup_;
      }
      McuManagerDBusProxy::UsmConvenience_IcyRoadWarningAttribute& McuManagerDBusProxy::getUsmConvenience_IcyRoadWarningAttribute() {
          return usmConvenience_IcyRoadWarning_;
      }
      McuManagerDBusProxy::UsmServiceInterval_ModeAttribute& McuManagerDBusProxy::getUsmServiceInterval_ModeAttribute() {
          return usmServiceInterval_Mode_;
      }
      McuManagerDBusProxy::UsmServiceInterval_EnableServiceIntervalAttribute& McuManagerDBusProxy::getUsmServiceInterval_EnableServiceIntervalAttribute() {
          return usmServiceInterval_EnableServiceInterval_;
      }
      McuManagerDBusProxy::UsmServiceInterval_ResetAttribute& McuManagerDBusProxy::getUsmServiceInterval_ResetAttribute() {
          return usmServiceInterval_Reset_;
      }
      McuManagerDBusProxy::UsmOther_FuelEconomyResetAttribute& McuManagerDBusProxy::getUsmOther_FuelEconomyResetAttribute() {
          return usmOther_FuelEconomyReset_;
      }
      McuManagerDBusProxy::UsmOther_FuelEconomyUnitAttribute& McuManagerDBusProxy::getUsmOther_FuelEconomyUnitAttribute() {
          return usmOther_FuelEconomyUnit_;
      }
      McuManagerDBusProxy::UsmOther_TemperatureUnitAttribute& McuManagerDBusProxy::getUsmOther_TemperatureUnitAttribute() {
          return usmOther_TemperatureUnit_;
      }
      McuManagerDBusProxy::UsmOther_TirePressureUnitAttribute& McuManagerDBusProxy::getUsmOther_TirePressureUnitAttribute() {
          return usmOther_TirePressureUnit_;
      }
      McuManagerDBusProxy::UsmOther_SpeedUnitAttribute& McuManagerDBusProxy::getUsmOther_SpeedUnitAttribute() {
          return usmOther_SpeedUnit_;
      }
      McuManagerDBusProxy::UsmOther_TorqueUnitAttribute& McuManagerDBusProxy::getUsmOther_TorqueUnitAttribute() {
          return usmOther_TorqueUnit_;
      }
      McuManagerDBusProxy::UsmOther_TurboBoostPressureUnitAttribute& McuManagerDBusProxy::getUsmOther_TurboBoostPressureUnitAttribute() {
          return usmOther_TurboBoostPressureUnit_;
      }
      McuManagerDBusProxy::UsmEcoVehicle_GreenZoneEVDriveAttribute& McuManagerDBusProxy::getUsmEcoVehicle_GreenZoneEVDriveAttribute() {
          return usmEcoVehicle_GreenZoneEVDrive_;
      }
      McuManagerDBusProxy::UsmEcoVehicle_CoastingGuideEnableAttribute& McuManagerDBusProxy::getUsmEcoVehicle_CoastingGuideEnableAttribute() {
          return usmEcoVehicle_CoastingGuideEnable_;
      }
      McuManagerDBusProxy::UsmEcoVehicle_CoastingGuideSoundAttribute& McuManagerDBusProxy::getUsmEcoVehicle_CoastingGuideSoundAttribute() {
          return usmEcoVehicle_CoastingGuideSound_;
      }
      McuManagerDBusProxy::UsmEcoVehicle_StartCoastingAttribute& McuManagerDBusProxy::getUsmEcoVehicle_StartCoastingAttribute() {
          return usmEcoVehicle_StartCoasting_;
      }
      McuManagerDBusProxy::UsmEcoVehicle_ChargingConnectorLockingModeAttribute& McuManagerDBusProxy::getUsmEcoVehicle_ChargingConnectorLockingModeAttribute() {
          return usmEcoVehicle_ChargingConnectorLockingMode_;
      }
      McuManagerDBusProxy::UsmEcoVehicle_ChargingConnectorConditionAttribute& McuManagerDBusProxy::getUsmEcoVehicle_ChargingConnectorConditionAttribute() {
          return usmEcoVehicle_ChargingConnectorCondition_;
      }
      McuManagerDBusProxy::UsmEcoVehicle_AuxiliaryBatterySaverPlusAttribute& McuManagerDBusProxy::getUsmEcoVehicle_AuxiliaryBatterySaverPlusAttribute() {
          return usmEcoVehicle_AuxiliaryBatterySaverPlus_;
      }
      McuManagerDBusProxy::UsmLanguageAttribute& McuManagerDBusProxy::getUsmLanguageAttribute() {
          return usmLanguage_;
      }
      McuManagerDBusProxy::UsmService_ReminderAttribute& McuManagerDBusProxy::getUsmService_ReminderAttribute() {
          return usmService_Reminder_;
      }
      McuManagerDBusProxy::UsmEcoVehicle_VolumeControlFunctionForVESSAttribute& McuManagerDBusProxy::getUsmEcoVehicle_VolumeControlFunctionForVESSAttribute() {
          return usmEcoVehicle_VolumeControlFunctionForVESS_;
      }
      McuManagerDBusProxy::LastTabInfoAttribute& McuManagerDBusProxy::getLastTabInfoAttribute() {
          return lastTabInfo_;
      }

McuManagerDBusProxy::NotifySteerWheelKeyEvent& McuManagerDBusProxy::getNotifySteerWheelKeyEvent() {
    return notifySteerWheelKey_;
}
McuManagerDBusProxy::NotifyIGNStateEvent& McuManagerDBusProxy::getNotifyIGNStateEvent() {
    return notifyIGNState_;
}
McuManagerDBusProxy::NotifyContentsGearStateEvent& McuManagerDBusProxy::getNotifyContentsGearStateEvent() {
    return notifyContentsGearState_;
}
McuManagerDBusProxy::NotifyEventContentsEvent& McuManagerDBusProxy::getNotifyEventContentsEvent() {
    return notifyEventContents_;
}
McuManagerDBusProxy::NotifyMasterWarnInfoEvent& McuManagerDBusProxy::getNotifyMasterWarnInfoEvent() {
    return notifyMasterWarnInfo_;
}
McuManagerDBusProxy::NotifyMasterWarnCmdEvent& McuManagerDBusProxy::getNotifyMasterWarnCmdEvent() {
    return notifyMasterWarnCmd_;
}
McuManagerDBusProxy::NotifySoundEvent& McuManagerDBusProxy::getNotifySoundEvent() {
    return notifySound_;
}

    void McuManagerDBusProxy::Command(const uint8_t &_id, const ::v1::proj::dcluster::McuManager::McuManagerTypes::CmdData &_data, CommonAPI::CallStatus &_internalCallStatus, bool &_result, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< uint8_t, CommonAPI::EmptyDeployment> deploy_id(_id, static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        CommonAPI::Deployable< ::v1::proj::dcluster::McuManager::McuManagerTypes::CmdData, CommonAPI::EmptyDeployment> deploy_data(_data, static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        CommonAPI::Deployable< bool, CommonAPI::EmptyDeployment> deploy_result(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< uint8_t, CommonAPI::EmptyDeployment >,
            CommonAPI::Deployable< ::v1::proj::dcluster::McuManager::McuManagerTypes::CmdData, CommonAPI::EmptyDeployment >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< bool,CommonAPI::EmptyDeployment>
            >
            >::callMethodWithReply(
        *this,
        "Command",
        "yay",
(_info ? _info : &CommonAPI::DBus::defaultCallInfo),
deploy_id, deploy_data,
_internalCallStatus,
deploy_result);
_result = deploy_result.getValue();
}
    std::future<CommonAPI::CallStatus> McuManagerDBusProxy::CommandAsync(const uint8_t &_id, const ::v1::proj::dcluster::McuManager::McuManagerTypes::CmdData &_data, CommandAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< uint8_t, CommonAPI::EmptyDeployment> deploy_id(_id, static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        CommonAPI::Deployable< ::v1::proj::dcluster::McuManager::McuManagerTypes::CmdData, CommonAPI::EmptyDeployment> deploy_data(_data, static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        CommonAPI::Deployable< bool, CommonAPI::EmptyDeployment> deploy_result(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        return CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< uint8_t, CommonAPI::EmptyDeployment >,
            CommonAPI::Deployable< ::v1::proj::dcluster::McuManager::McuManagerTypes::CmdData, CommonAPI::EmptyDeployment >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< bool,CommonAPI::EmptyDeployment>
            >
            >::callMethodAsync(
        *this,
        "Command",
        "yay",
        (_info ? _info : &CommonAPI::DBus::defaultCallInfo),
        deploy_id, deploy_data,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< bool, CommonAPI::EmptyDeployment > _result) {
            if (_callback)
                _callback(_internalCallStatus, _result.getValue());
        },
        std::make_tuple(deploy_result));
    }


void McuManagerDBusProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
          ownVersionMajor = 1;
          ownVersionMinor = 0;
      }

      } // namespace McuManager
      } // namespace dcluster
      } // namespace proj
      } // namespace v1
