/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.1.12.v201907221221.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include "McuManagerTypesDBusDeployment.hpp"

namespace v1 {
namespace proj {
namespace dcluster {
namespace McuManager {
namespace McuManagerTypes_ {

// typecollection-specific deployments

} // namespace McuManagerTypes_
} // namespace McuManager
} // namespace dcluster
} // namespace proj
} // namespace v1
