/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v202001100728.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_PROJ_TESTCODE_Test_Code_STUB_HPP_
#define V1_PROJ_TESTCODE_Test_Code_STUB_HPP_

#include <functional>
#include <sstream>




#include <v1/proj/testcode/TestCode.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <cstdint>
#include <vector>

#include <mutex>

#include <CommonAPI/Stub.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace proj {
namespace testcode {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service TestCode. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class TestCodeStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual TestCode {
 public:
    ///Notifies all remote listeners about a change of value of the attribute speedType.
    virtual void fireSpeedTypeAttributeChanged(const ::v1::proj::testcode::TestCode::SpeedType& speedType) = 0;
    ///Notifies all remote listeners about a change of value of the attribute speedValue.
    virtual void fireSpeedValueAttributeChanged(const int32_t& speedValue) = 0;



    virtual void deactivateManagedInstances() = 0;

    void lockSpeedTypeAttribute(bool _lockAccess) {
        if (_lockAccess) {
            speedTypeMutex_.lock();
        } else {
            speedTypeMutex_.unlock();
        }
    }
    void lockSpeedValueAttribute(bool _lockAccess) {
        if (_lockAccess) {
            speedValueMutex_.lock();
        } else {
            speedValueMutex_.unlock();
        }
    }

protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */

    std::recursive_mutex speedTypeMutex_;
    std::recursive_mutex speedValueMutex_;
};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for TestCode.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class TestCodeStubRemoteEvent
{
public:
    virtual ~TestCodeStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service TestCode to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class TestCodeStub
    : public virtual CommonAPI::Stub<TestCodeStubAdapter, TestCodeStubRemoteEvent>
{
public:
    typedef std::function<void ()>setSpeedTypeReply_t;
    typedef std::function<void (TestCode::SpeedType _show)>getSpeedTypeReply_t;
    typedef std::function<void ()>setSpeedValueReply_t;
    typedef std::function<void (int32_t _show)>getSpeedValueReply_t;

    virtual ~TestCodeStub() {}
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> clientId) = 0;
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }

    /// Provides getter access to the attribute speedType
    virtual const ::v1::proj::testcode::TestCode::SpeedType &getSpeedTypeAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireSpeedTypeAttributeChanged(::v1::proj::testcode::TestCode::SpeedType _value) {
    auto stubAdapter = CommonAPI::Stub<TestCodeStubAdapter, TestCodeStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireSpeedTypeAttributeChanged(_value);
    }
    void lockSpeedTypeAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<TestCodeStubAdapter, TestCodeStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockSpeedTypeAttribute(_lockAccess);
    }
    /// Provides getter access to the attribute speedValue
    virtual const int32_t &getSpeedValueAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireSpeedValueAttributeChanged(int32_t _value) {
    auto stubAdapter = CommonAPI::Stub<TestCodeStubAdapter, TestCodeStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireSpeedValueAttributeChanged(_value);
    }
    void lockSpeedValueAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<TestCodeStubAdapter, TestCodeStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockSpeedValueAttribute(_lockAccess);
    }

    /// This is the method that will be called on remote calls on the method setSpeedType.
    virtual void setSpeedType(const std::shared_ptr<CommonAPI::ClientId> _client, TestCode::SpeedType _type, setSpeedTypeReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method getSpeedType.
    virtual void getSpeedType(const std::shared_ptr<CommonAPI::ClientId> _client, getSpeedTypeReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method setSpeedValue.
    virtual void setSpeedValue(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _show, setSpeedValueReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method getSpeedValue.
    virtual void getSpeedValue(const std::shared_ptr<CommonAPI::ClientId> _client, getSpeedValueReply_t _reply) = 0;

    
    using CommonAPI::Stub<TestCodeStubAdapter, TestCodeStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<TestCodeStubAdapter, TestCodeStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<TestCodeStubAdapter, TestCodeStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef TestCodeStubRemoteEvent RemoteEventType;
    typedef TestCode StubInterface;
};

} // namespace testcode
} // namespace proj
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_PROJ_TESTCODE_Test_Code_STUB_HPP_
