/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v202001100728.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_PROJ_TESTCODE_Test_Code_STUB_DEFAULT_HPP_
#define V1_PROJ_TESTCODE_Test_Code_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/proj/testcode/TestCodeStub.hpp>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace proj {
namespace testcode {

/**
 * Provides a default implementation for TestCodeStubRemoteEvent and
 * TestCodeStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT TestCodeStubDefault
    : public virtual TestCodeStub {
public:
    COMMONAPI_EXPORT TestCodeStubDefault();

    COMMONAPI_EXPORT TestCodeStubRemoteEvent* initStubAdapter(const std::shared_ptr< TestCodeStubAdapter> &_adapter);

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client);

    COMMONAPI_EXPORT virtual const ::v1::proj::testcode::TestCode::SpeedType& getSpeedTypeAttribute();
    COMMONAPI_EXPORT virtual const ::v1::proj::testcode::TestCode::SpeedType& getSpeedTypeAttribute(const std::shared_ptr<CommonAPI::ClientId> _client);
    COMMONAPI_EXPORT virtual void setSpeedTypeAttribute(::v1::proj::testcode::TestCode::SpeedType _value);
    COMMONAPI_EXPORT virtual const int32_t& getSpeedValueAttribute();
    COMMONAPI_EXPORT virtual const int32_t& getSpeedValueAttribute(const std::shared_ptr<CommonAPI::ClientId> _client);
    COMMONAPI_EXPORT virtual void setSpeedValueAttribute(int32_t _value);

    COMMONAPI_EXPORT virtual void setSpeedType(const std::shared_ptr<CommonAPI::ClientId> _client, TestCode::SpeedType _type, setSpeedTypeReply_t _reply);
    COMMONAPI_EXPORT virtual void getSpeedType(const std::shared_ptr<CommonAPI::ClientId> _client, getSpeedTypeReply_t _reply);
    COMMONAPI_EXPORT virtual void setSpeedValue(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _show, setSpeedValueReply_t _reply);
    COMMONAPI_EXPORT virtual void getSpeedValue(const std::shared_ptr<CommonAPI::ClientId> _client, getSpeedValueReply_t _reply);


    
protected:
    COMMONAPI_EXPORT virtual bool trySetSpeedTypeAttribute(::v1::proj::testcode::TestCode::SpeedType _value);
    COMMONAPI_EXPORT virtual bool validateSpeedTypeAttributeRequestedValue(const ::v1::proj::testcode::TestCode::SpeedType &_value);
    COMMONAPI_EXPORT virtual bool trySetSpeedValueAttribute(int32_t _value);
    COMMONAPI_EXPORT virtual bool validateSpeedValueAttributeRequestedValue(const int32_t &_value);
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual TestCodeStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(TestCodeStubDefault *_defaultStub);




    private:
        TestCodeStubDefault *defaultStub_;
    };
protected:
    TestCodeStubDefault::RemoteEventHandler remoteEventHandler_;

private:

    ::v1::proj::testcode::TestCode::SpeedType speedTypeAttributeValue_ {};
    int32_t speedValueAttributeValue_ {};

    CommonAPI::Version interfaceVersion_;
};

} // namespace testcode
} // namespace proj
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_PROJ_TESTCODE_Test_Code_STUB_DEFAULT
