/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v202001100728.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1/proj/testcode/TestCodeStubDefault.hpp>
#include <assert.h>

namespace v1 {
namespace proj {
namespace testcode {

TestCodeStubDefault::TestCodeStubDefault():
        remoteEventHandler_(this),
        interfaceVersion_(TestCode::getInterfaceVersion()) {
}

const CommonAPI::Version& TestCodeStubDefault::getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
    (void)_client;
    return interfaceVersion_;
}

TestCodeStubRemoteEvent* TestCodeStubDefault::initStubAdapter(const std::shared_ptr< TestCodeStubAdapter> &_adapter) {
    CommonAPI::Stub<TestCodeStubAdapter, TestCodeStubRemoteEvent>::stubAdapter_ = _adapter;
    return &remoteEventHandler_;
}

 const ::v1::proj::testcode::TestCode::SpeedType& TestCodeStubDefault::getSpeedTypeAttribute() {
     return speedTypeAttributeValue_;
 }

 const ::v1::proj::testcode::TestCode::SpeedType& TestCodeStubDefault::getSpeedTypeAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
     (void)_client;
     return getSpeedTypeAttribute();
 }

 void TestCodeStubDefault::setSpeedTypeAttribute(::v1::proj::testcode::TestCode::SpeedType _value) {
     std::shared_ptr<TestCodeStubAdapter> stubAdapter = CommonAPI::Stub<TestCodeStubAdapter,
     TestCodeStubRemoteEvent>::stubAdapter_.lock();
     if(stubAdapter) {
         stubAdapter->lockSpeedTypeAttribute(true);
         const bool valueChanged = (speedTypeAttributeValue_ != _value);
         if (valueChanged) {
             speedTypeAttributeValue_ = std::move(_value);
             fireSpeedTypeAttributeChanged(speedTypeAttributeValue_);
         }
         stubAdapter->lockSpeedTypeAttribute(false);
     } else {
         const bool valueChanged = trySetSpeedTypeAttribute(std::move(_value));
         if (valueChanged) {
             fireSpeedTypeAttributeChanged(speedTypeAttributeValue_);
         }
     }
}

 bool TestCodeStubDefault::trySetSpeedTypeAttribute(::v1::proj::testcode::TestCode::SpeedType _value) {
     if (!validateSpeedTypeAttributeRequestedValue(_value))
         return false;

     bool valueChanged;
     std::shared_ptr<TestCodeStubAdapter> stubAdapter = CommonAPI::Stub<TestCodeStubAdapter, TestCodeStubRemoteEvent>::stubAdapter_.lock();
     if(stubAdapter) {
         stubAdapter->lockSpeedTypeAttribute(true);
         valueChanged = (speedTypeAttributeValue_ != _value);
         speedTypeAttributeValue_ = std::move(_value);
         stubAdapter->lockSpeedTypeAttribute(false);
     } else {
         valueChanged = (speedTypeAttributeValue_ != _value);
         speedTypeAttributeValue_ = std::move(_value);
     }

     return valueChanged;
 }

 bool TestCodeStubDefault::validateSpeedTypeAttributeRequestedValue(const ::v1::proj::testcode::TestCode::SpeedType &_value) {
     (void)_value;
     return _value.validate();
 }


 const int32_t& TestCodeStubDefault::getSpeedValueAttribute() {
     return speedValueAttributeValue_;
 }

 const int32_t& TestCodeStubDefault::getSpeedValueAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
     (void)_client;
     return getSpeedValueAttribute();
 }

 void TestCodeStubDefault::setSpeedValueAttribute(int32_t _value) {
     std::shared_ptr<TestCodeStubAdapter> stubAdapter = CommonAPI::Stub<TestCodeStubAdapter,
     TestCodeStubRemoteEvent>::stubAdapter_.lock();
     if(stubAdapter) {
         stubAdapter->lockSpeedValueAttribute(true);
         const bool valueChanged = (speedValueAttributeValue_ != _value);
         if (valueChanged) {
             speedValueAttributeValue_ = std::move(_value);
             fireSpeedValueAttributeChanged(speedValueAttributeValue_);
         }
         stubAdapter->lockSpeedValueAttribute(false);
     } else {
         const bool valueChanged = trySetSpeedValueAttribute(std::move(_value));
         if (valueChanged) {
             fireSpeedValueAttributeChanged(speedValueAttributeValue_);
         }
     }
}

 bool TestCodeStubDefault::trySetSpeedValueAttribute(int32_t _value) {
     if (!validateSpeedValueAttributeRequestedValue(_value))
         return false;

     bool valueChanged;
     std::shared_ptr<TestCodeStubAdapter> stubAdapter = CommonAPI::Stub<TestCodeStubAdapter, TestCodeStubRemoteEvent>::stubAdapter_.lock();
     if(stubAdapter) {
         stubAdapter->lockSpeedValueAttribute(true);
         valueChanged = (speedValueAttributeValue_ != _value);
         speedValueAttributeValue_ = std::move(_value);
         stubAdapter->lockSpeedValueAttribute(false);
     } else {
         valueChanged = (speedValueAttributeValue_ != _value);
         speedValueAttributeValue_ = std::move(_value);
     }

     return valueChanged;
 }

 bool TestCodeStubDefault::validateSpeedValueAttributeRequestedValue(const int32_t &_value) {
     (void)_value;
     return true;
 }



void TestCodeStubDefault::setSpeedType(const std::shared_ptr<CommonAPI::ClientId> _client, TestCode::SpeedType _type, setSpeedTypeReply_t _reply) {
    (void)_client;
    (void)_type;
    _reply();
}

void TestCodeStubDefault::getSpeedType(const std::shared_ptr<CommonAPI::ClientId> _client, getSpeedTypeReply_t _reply) {
    (void)_client;
    TestCode::SpeedType show = TestCode::SpeedType::SPEED_KIL;
    if (!show.validate()) {
        return;
    }
    _reply(show);
}

void TestCodeStubDefault::setSpeedValue(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _show, setSpeedValueReply_t _reply) {
    (void)_client;
    (void)_show;
    _reply();
}

void TestCodeStubDefault::getSpeedValue(const std::shared_ptr<CommonAPI::ClientId> _client, getSpeedValueReply_t _reply) {
    (void)_client;
    int32_t show = 0;
    _reply(show);
}




TestCodeStubDefault::RemoteEventHandler::RemoteEventHandler(TestCodeStubDefault *_defaultStub)
    : 
      defaultStub_(_defaultStub) {
}

} // namespace testcode
} // namespace proj
} // namespace v1
