/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v202001100728.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_PROJ_TESTCODE_Test_Code_PROXY_HPP_
#define V1_PROJ_TESTCODE_Test_Code_PROXY_HPP_

#include <v1/proj/testcode/TestCodeProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/AttributeExtension.hpp>
#include <CommonAPI/Factory.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace proj {
namespace testcode {

template <typename ... _AttributeExtensions>
class TestCodeProxy
    : virtual public TestCode,
      virtual public TestCodeProxyBase,
      virtual public _AttributeExtensions... {
public:
    TestCodeProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~TestCodeProxy();

    typedef TestCode InterfaceType;


    /**
     * Returns the wrapper class that provides access to the attribute speedType.
     */
    virtual SpeedTypeAttribute& getSpeedTypeAttribute() {
        return delegate_->getSpeedTypeAttribute();
    }
    /**
     * Returns the wrapper class that provides access to the attribute speedValue.
     */
    virtual SpeedValueAttribute& getSpeedValueAttribute() {
        return delegate_->getSpeedValueAttribute();
    }


    /**
     * Calls setSpeedType with synchronous semantics.
     *
    * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void setSpeedType(const TestCode::SpeedType &_type, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls setSpeedType with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> setSpeedTypeAsync(const TestCode::SpeedType &_type, SetSpeedTypeAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls getSpeedType with synchronous semantics.
     *
    * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void getSpeedType(CommonAPI::CallStatus &_internalCallStatus, TestCode::SpeedType &_show, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls getSpeedType with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> getSpeedTypeAsync(GetSpeedTypeAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls setSpeedValue with synchronous semantics.
     *
    * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void setSpeedValue(const int32_t &_show, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls setSpeedValue with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> setSpeedValueAsync(const int32_t &_show, SetSpeedValueAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls getSpeedValue with synchronous semantics.
     *
    * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void getSpeedValue(CommonAPI::CallStatus &_internalCallStatus, int32_t &_show, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls getSpeedValue with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> getSpeedValueAsync(GetSpeedValueAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

 private:
    std::shared_ptr< TestCodeProxyBase> delegate_;
};

typedef TestCodeProxy<> TestCodeProxyDefault;

namespace TestCodeExtensions {
    template <template <typename > class _ExtensionType>
    class SpeedTypeAttributeExtension {
     public:
        typedef _ExtensionType< TestCodeProxyBase::SpeedTypeAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< TestCodeProxyBase::SpeedTypeAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        SpeedTypeAttributeExtension(TestCodeProxyBase& proxy): attributeExtension_(proxy.getSpeedTypeAttribute()) {
        }
    
        inline extension_type& getSpeedTypeAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

    template <template <typename > class _ExtensionType>
    class SpeedValueAttributeExtension {
     public:
        typedef _ExtensionType< TestCodeProxyBase::SpeedValueAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< TestCodeProxyBase::SpeedValueAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        SpeedValueAttributeExtension(TestCodeProxyBase& proxy): attributeExtension_(proxy.getSpeedValueAttribute()) {
        }
    
        inline extension_type& getSpeedValueAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

} // namespace TestCodeExtensions

//
// TestCodeProxy Implementation
//
template <typename ... _AttributeExtensions>
TestCodeProxy<_AttributeExtensions...>::TestCodeProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< TestCodeProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< TestCodeProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
TestCodeProxy<_AttributeExtensions...>::~TestCodeProxy() {
}

template <typename ... _AttributeExtensions>
void TestCodeProxy<_AttributeExtensions...>::setSpeedType(const TestCode::SpeedType &_type, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
    if (!_type.validate()) {
        _internalCallStatus = CommonAPI::CallStatus::INVALID_VALUE;
        return;
    }
    delegate_->setSpeedType(_type, _internalCallStatus, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> TestCodeProxy<_AttributeExtensions...>::setSpeedTypeAsync(const TestCode::SpeedType &_type, SetSpeedTypeAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    if (!_type.validate()) {
        _callback(CommonAPI::CallStatus::INVALID_VALUE);
        std::promise<CommonAPI::CallStatus> promise;
        promise.set_value(CommonAPI::CallStatus::INVALID_VALUE);
        return promise.get_future();
    }
    return delegate_->setSpeedTypeAsync(_type, _callback, _info);
}
template <typename ... _AttributeExtensions>
void TestCodeProxy<_AttributeExtensions...>::getSpeedType(CommonAPI::CallStatus &_internalCallStatus, TestCode::SpeedType &_show, const CommonAPI::CallInfo *_info) {
    delegate_->getSpeedType(_internalCallStatus, _show, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> TestCodeProxy<_AttributeExtensions...>::getSpeedTypeAsync(GetSpeedTypeAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->getSpeedTypeAsync(_callback, _info);
}
template <typename ... _AttributeExtensions>
void TestCodeProxy<_AttributeExtensions...>::setSpeedValue(const int32_t &_show, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
    delegate_->setSpeedValue(_show, _internalCallStatus, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> TestCodeProxy<_AttributeExtensions...>::setSpeedValueAsync(const int32_t &_show, SetSpeedValueAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->setSpeedValueAsync(_show, _callback, _info);
}
template <typename ... _AttributeExtensions>
void TestCodeProxy<_AttributeExtensions...>::getSpeedValue(CommonAPI::CallStatus &_internalCallStatus, int32_t &_show, const CommonAPI::CallInfo *_info) {
    delegate_->getSpeedValue(_internalCallStatus, _show, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> TestCodeProxy<_AttributeExtensions...>::getSpeedValueAsync(GetSpeedValueAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->getSpeedValueAsync(_callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &TestCodeProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool TestCodeProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool TestCodeProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& TestCodeProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& TestCodeProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


} // namespace testcode
} // namespace proj
} // namespace v1

namespace CommonAPI {
template<template<typename > class _AttributeExtension>
struct DefaultAttributeProxyHelper< ::v1::proj::testcode::TestCodeProxy,
    _AttributeExtension> {
    typedef typename ::v1::proj::testcode::TestCodeProxy<
            ::v1::proj::testcode::TestCodeExtensions::SpeedTypeAttributeExtension<_AttributeExtension>, 
            ::v1::proj::testcode::TestCodeExtensions::SpeedValueAttributeExtension<_AttributeExtension>
    > class_t;
};
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_PROJ_TESTCODE_Test_Code_PROXY_HPP_
